const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  getApps: () => ipcRenderer.invoke('get-apps'),
  getUsers: () => ipcRenderer.invoke('get-users'),
  saveApp: (appData) => ipcRenderer.invoke('save-app', appData),
  saveUsers: (users) => ipcRenderer.invoke('save-users', users),
  launchApp: (id, path, gameMeta) => ipcRenderer.invoke('launch-app', id, path, gameMeta),
  selectFile: () => ipcRenderer.invoke('select-file'),
  selectImage: () => ipcRenderer.invoke('select-image'),
  selectVideo: () => ipcRenderer.invoke('select-video'),
  updateApp: (appData) => ipcRenderer.invoke('update-app', appData),
  closeApp: () => ipcRenderer.invoke('close-app'),
  fetchGameData: (title) => ipcRenderer.invoke('fetch-game-data', title),
  fetchSteamGridData: (title) => ipcRenderer.invoke('fetch-steamgrid-data', title),
  fetchSteamGridAssets: (title) => ipcRenderer.invoke('fetch-steamgrid-assets', title),
  getStorageInfo: () => ipcRenderer.invoke('get-storage-info'),
  openScreenshots: () => ipcRenderer.invoke('open-screenshots'),
  openGameLocation: (path) => ipcRenderer.invoke('open-game-location', path),
  deleteApp: (id) => ipcRenderer.invoke('delete-app', id),
  fetchNews: () => ipcRenderer.invoke('fetch-news'),
  selectCaptureFolder: () => ipcRenderer.invoke('select-capture-folder'),
  getLatestCapture: (folderPath) => ipcRenderer.invoke('get-latest-capture', folderPath),
  steamLogin: () => ipcRenderer.invoke('steam-login'),
  getSteamInstalledApps: () => ipcRenderer.invoke('get-steam-installed-apps'),
  hideGameOverlay: () => ipcRenderer.invoke('hide-game-overlay'),
  restoreLauncherFromGame: () => ipcRenderer.invoke('restore-launcher-from-game'),
  getRunningGame: () => ipcRenderer.invoke('get-running-game'),
  onGameClosed: (callback) => ipcRenderer.on('game-closed', (_event, id) => callback(id)),
  removeGameClosedListener: () => ipcRenderer.removeAllListeners('game-closed'),
  onOverlayOpened: (callback) => ipcRenderer.on('overlay-opened', (_event, game) => callback(game)),
  removeOverlayOpenedListener: () => ipcRenderer.removeAllListeners('overlay-opened'),
  onOverlayClosed: (callback) => ipcRenderer.on('returned-to-game', () => callback()),
  removeOverlayClosedListener: () => ipcRenderer.removeAllListeners('returned-to-game'),
  onLauncherRestoredFromGame: (callback) => ipcRenderer.on('launcher-restored-from-game', (_event, game) => callback(game)),
  removeLauncherRestoredFromGameListener: () => ipcRenderer.removeAllListeners('launcher-restored-from-game'),
});

